application: farmalium
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers: # static then dynamic
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

##################################################
- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/bootstrap/css

- url: /fonts
  static_dir: static/fonts

- url: /partials
  static_dir: static/partials

#- url: /
#  static_files: templates/index.html
#  upload: templates/index\.html
#  secure: always

#####################################


#Este es el del ejemplo sql
#- url: /
#  script: main.app

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "latest"

- name: MySQLdb
  version: "latest"

#Esto es para manejar templates de html
- name: jinja2
  version: latest
